### ISSUE TITLE
wrong metadata in novasama vault

### ISSUE THREAD

**Issue by hitchhooker** [paseo-network/runtimes#135]
https://metadata.novasama.io/?tab=0#/paseo

has wrong metadata, probably from old network or so. end result being that paseo hw wallets cant be accessed in airgap fashion and used as training ground for other networks.

**Comment by hbulgarini** [comment]
Hi! thank you very much for reporting this issue.

We have found the reason for the miss-match and to fix it we need some coordination with validators to fix it across the network.

As we usually manage this kind of reports in the support repository, i will close this issue in favor of https://github.com/paseo-network/support/issues/103
