### ISSUE TITLE
Wrong SS58 prefix after in paseo-1003000

### ISSUE THREAD

**Issue by pgolovkin** [paseo-network/runtimes#137]
Seems that Paseo metadata SS58 prefix is different in storage query and RPC properties call.

That leads to error on creating QR codes for [Metadata portal](https://github.com/novasamatech/metadata-portal/issues/1017) 

<img width="1213" alt="image" src="https://github.com/user-attachments/assets/2df5c4f9-0d37-43e8-9b17-5c431ac9d523">
<img width="1227" alt="image" src="https://github.com/user-attachments/assets/6aefd305-aba3-4c97-b64c-3cb42f9782b9">

**Comment by hbulgarini** [comment]
Hi! thank you very much for reporting this issue.

We have found the reason for the miss-match and to fix it we need some coordination with validators to fix it across the network.

As we usually manage this kind of reports in the support repository, i will close this issue in favor of https://github.com/paseo-network/support/issues/103
