### ISSUE TITLE
Wrong SS58Format on the chainspecs

### ISSUE THREAD

**Issue by josepot** [paseo-network/runtimes#152]
The on-chain value for the `system.ss58Prefix` constant on the Paseo relay chain is `0`. However, the properites entry of the chainspecs have `42`. We keep on receiving issues on the Polkadot-API repo because of this 😬.

**Comment by hbulgarini** [comment]
Thanks for reporting this. As it was clarified, the issue was addressed here:

https://github.com/paseo-network/support/issues/103

Polkadot API FTW!
