### ISSUE TITLE
Set the chain_specs for Paseo Network.

### ISSUE THREAD

**Issue by hbulgarini** [paseo-network/runtimes#3]
Use the chain spec tool to generate paseo network.

**Comment by al3mart** [comment]
Latest changes on https://github.com/paseo-network/runtimes/tree/feat-chain-spec-generator can generate the spec for paseo network.

The last nit to add in that front is the parameters corresponding to the network launch. Validator keys and such.

Next step will be reviewing the state of the system chains spec generation.

**Comment by hbulgarini** [comment]
https://github.com/paseo-network/runtimes/blob/main/chain-specs/paseo.raw.json
