### ISSUE TITLE
Add XCM runtime APIs in Paseo relay and system parachains

### ISSUE THREAD

**Issue by franciscoaguirre** [paseo-network/runtimes#93]
We recently added the [XcmPaymentApi](https://github.com/paritytech/polkadot-sdk/pull/3607) and [DryRunApi](https://github.com/paritytech/polkadot-sdk/pull/3872) to [westend and rococo relays and system parachains](https://github.com/paritytech/polkadot-sdk/pull/4634).
[There's an open PR](https://github.com/polkadot-fellows/runtimes/pull/380) to add them to the fellowship runtime as well.
It'd be good to add them to Paseo as well.

The way to do it is detailed in the dry run api PR, it also has an example of how to use them.

**Comment by hbulgarini** [comment]
Hello @franciscoaguirre,

Please take into account that Paseo follows Polkadot releases with minor changes to the current runtime. This was specifically asked by teams needing a stable environment to test their use cases with no downtimes as its happening now in Rococo.

So as soon as this feature is included the corresponding fellowship release, this feature will be deployed in Paseo.
